// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	FeedID        string
	Name          string
	Url           string
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	FeedFollowID string
	FeedID       string
	FollowerID   string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	UserID    string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
